const Projects =[
    {id: 10, 
        name: "Datatys", 
        description: "Platform for managing, processing and visualizing sensor and IoT data.",
        photo: "img/projects/datatys.png",
        album: [ {photo: "img/projects/10/photo1.png"},
        {photo: "img/projects/10/photo2.png"},
        {photo: "img/projects/10/photo3.png"},
        {photo: "img/projects/10/photo4.png"},
        {photo: "img/projects/10/photo5.png"},
        {photo: "img/projects/10/photo6.png"},
        {photo: "img/projects/10/photo7.png"},
        ],
        url :'',
        urlbool: false,
        accesweb: '',
        description2:'Joining the Datatys team to contribute to the development of a web application for instrumentation projects requiring data management to facilitate data tracking.',
        Functional: ['Graph management', 'Alert management', 'Project management', 'Sensor management', 'Map management'],
        Tags:  ['ReactJS, MaterialUi, Redux, NodeJs, ExpressJs,Python, PostgreSQL, AWS, Lambdas, Serverless, Git, Notion, Scrum' ],
        company:'Socotec Monitoring',
        start: '2021.12.08',
        end: 'Present',
    },
    {id: 1, 
    name: "3aweni Social Network", 
    description: "3aweni is a professional social network that aims to help people look for job offers.", 
    photo: "img/projects/3aweni3.png",
    album: [ {photo: "img/projects/1/photo1.png"},
    {photo: "img/projects/1/photo2.png"},
    {photo: "img/projects/1/photo3.png"},
    {photo: "img/projects/1/photo4.png"},
    {photo: "img/projects/1/photo5.png"},
    {photo: "img/projects/1/photo6.png"}
    ],
    description2: "3aweni is a professional social network created by 6 members that aims to help people look for job offers. In addition, thanks to this website, users who want to enlarge their knowledges can register in our courses and have certificates in different domains. There is also a dedicated area for sharing problems and posts to facilitate interaction and communication between users. Also, 3aweni help people having projects that need the organization by offering them the opportunity to create professional groups where they can organize their work on a table of tasks.",
    Functional: ['Post management', 'Comment management', 'Job Management', 'Course management', 'Group management', 'Page management', 'Meet Management'],
    url :'Website',
    urlbool: true,
    accesweb: 'https://3aweni.netlify.app/',
    Tags:  ['ReactJs, Ngrx, NodeJs, ExpressJs, MongoDB, Heroku,Netlify, Git, SEM'],
    company:'X',
    start: '2021.02.01',
    end: '2021.06.17',
}
     ,
     {id: 9, 
        name: "Devops Project", 
        description: "Implement all the links in the delivery chain of a Spring Boot application.",
        photo: "img/projects/timesheet.png",
        album: [ {photo: "img/projects/9/photo1.png"},
        {photo: "img/projects/9/photo2.png"},
        {photo: "img/projects/9/photo3.png"},
        ],
        description2: ['Apply Maven (command line) commands on our project (clean, install, package, ....)', 'Add lines of code to log (Log4j info debug, error, etc.).', 'Add JUnit to test multiple services.', 'Launch Sonar on our project.',
        'Create a Nexus Repo and put our project deliverable on Nexus', 'Configure Jenkins to automate the above tasks.', 'Continuous Delivery with Docker.' , 'Configure Email Notification in Jenkins'
        ],
        Functional: [],
        url :'Git Link',
        urlbool: true,
        accesweb: 'https://github.com/Samar-web-prog/Devops',
        Tags:  ['SpringBoot, java, Sonar, Jenkins, Junit,Log4j, Nexus,Github, Docker'],
        company:'Esprit',
        start: '2021.09.01',
        end: '2021.11.30',
    },
    {id: 11, 
        name: "Microservices Project", 
        description: "Microservices project",
        photo: "img/projects/microservice.png",
        album: [ {photo: "img/projects/11/photo1.png"},
        {photo: "img/projects/11/photo2.png"},
        {photo: "img/projects/11/photo3.png"},
        {photo: "img/projects/11/photo4.png"}
        ],
        description2: ['Develop micro-services with spring boot and nodejs','BDs are: H2, mysql and mongoDB', 'The Gateway (Proxy) for the configuration of micro-service routes.', 'Deploy microservices on containers', 'Ensure the security of the microservices architecture.'],
        Functional: [],
        url :'Git Link',
        urlbool: true,
        accesweb: 'https://github.com/siwarhassen/microservice',
        Tags:  ['Angular, Springboot, NodeJs, ExpressJS, MySQL, H2, Microservices, Github'],
        company:'Esprit',
        start: '2021.09.02',
        end: '2021.11.27',
    },
    {id: 2, 
    name: "BricoFast (ux design)", 
    description: "Learn the basics of web product development through the design thinking process.",
     photo: "img/projects/brico.png",
     album: [ {photo: "img/projects/2/photo1.png"},
     {photo: "img/projects/2/photo2.png"},
     {photo: "img/projects/2/photo3.png"},
     {photo: "img/projects/2/photo4.png"},
     {photo: "img/projects/2/photo5.png"},
     {photo: "img/projects/2/photo6.png"},
     {photo: "img/projects/2/photo7.png"},
     {photo: "img/projects/2/photo8.png"}
     ],
     Functional: [],
     url :'',
     urlbool: false,
     accesweb: '',
     Tags:  ['Figma, Adobe Photoshop, Consider Ly, UX Design'],
     company:'Esprit',
     start: '2021.09.02',
     end: '2021.11.29',
    },
     {id: 8, 
        name: "Preclinic", 
        description: "A platform that makes it easier for Proxym employees to request appointments online with doctors",
        photo: "img/projects/preclinic.png",
        album: [ {photo: "img/projects/8/photo1.png"},
        {photo: "img/projects/8/photo2.png"},
        {photo: "img/projects/8/photo3.png"},
        {photo: "img/projects/8/photo4.png"},
        {photo: "img/projects/8/photo5.png"},
        {photo: "img/projects/8/photo6.png"},
        {photo: "img/projects/8/photo7.png"},
        {photo: "img/projects/8/photo8.png"},
        {photo: "img/projects/8/photo9.png"},
        {photo: "img/projects/8/photo10.png"},
        {photo: "img/projects/8/photo11.png"},
        {photo: "img/projects/8/photo12.png"},
        {photo: "img/projects/8/photo13.png"},
        ],
        description2: "During this internship, I was asked to design and develop a platform that facilitates the Proxym staff’s request for online appointments with doctors who are agreed with the company.",
        Functional: ['Consult the list of doctors', 'Check the status of appointments', 'View appointment history', 'Cancel an appointment', 'Make an appointment', 'Find a doctor', 'Manage appointments(doctors part)', 'Manage work schedule', 'Manage availability', 'View Notifications' ],
        url :'Git Link',
        urlbool: false,
        accesweb: '',
        Tags:  ['Angular NX, Ngrx, NestJS,MySQL, Workspace NX,Github, Bitbucket, Microservices '],
        company:'Proxym IT',
        start: '2021.07.11',
        end: '2021.09.11',
    },
        {id: 6, 
            name: "VideDressing", 
            description: "Online wardrobe sale where people can buy, sell or trade new or used fashion items.",
            photo: "img/projects/videdressing.png",
            album: [ {photo: "img/projects/6/photo1.png"},
            {photo: "img/projects/6/photo2.png"},
            {photo: "img/projects/6/photo3.png"},
            {photo: "img/projects/6/photo4.png"},
            {photo: "img/projects/6/photo5.png"},
            {photo: "img/projects/6/photo6.png"},
            {photo: "img/projects/6/photo7.png"},
            {photo: "img/projects/6/photo8.png"},
            {photo: "img/projects/6/photo9.png"},
            {photo: "img/projects/6/photo10.png"},
            {photo: "img/projects/6/photo11.png"},
            {photo: "img/projects/6/photo12.png"},
            ],
            description2: " A social fashion network whose goal is simple: allow people to renew their wardrobe by selling their unused clothes and to buy others at low prices.",
            Functional: ['Product management', 'Order management', 'Caddy management '],
            url :'Git Link',
            urlbool: true,
            accesweb: 'https://github.com/siwarhassen/projetAngular',
            Tags:  ['Angular, SpringBoot, Github, MySQL'],
            company:'',
            start: '2020.11.01',
            end: '2020.12.31',
        },
            {id: 7, 
                name: "HVAC", 
                description: "HVAC is a web application that offers to help users sell or buy a car.",
                photo: "img/projects/hvac.png",
                album: [ {photo: "img/projects/7/photo1.png"},
                {photo: "img/projects/7/photo2.png"},
                {photo: "img/projects/7/photo3.png"},
                {photo: "img/projects/7/photo4.png"}
                ],
                description2:"This application offers a wide selection of vehicles and allows you to sort by brand, model, MPG, price, etc. You will see the initial prices and no haggling, so that you know what you will pay in advance. Users can also sell their cars",
                Functional: ['Car management', 'Comment management', 'Manage favorites'],
                url :'Git Link',
                urlbool: true,
                accesweb: 'https://github.com/siwarhassen/automobile',
                Tags:  ['Angular, Ngrx, NodeJS,Mongodb, SEM,Git'],
                company:'Proxym IT',
                start: '2020.07.09',
                end: '2020.09.09',
            },
    { id: 3, 
      name: "Tunisian Got Talent", 
      description: "Is a Multiplatform application: (web, desktop and mobile), dedicated for the talented.",
      photo: "img/projects/tunisian.png",
      album: [ {photo: "img/projects/3/photo5.png"},
      {photo: "img/projects/3/photo1.png"},
      {photo: "img/projects/3/photo2.png"},
      {photo: "img/projects/3/photo3.png"},
      {photo: "img/projects/3/photo4.png"},
      {photo: "img/projects/3/photo6.png"}
      ],
      description2: "Tunisia’s got talent is a multiplatform application: (web ,desktop and mobile), dedicated to talented  . This application is carried out as part of an integrated project in group of 5 people. As the development of this Application is carried out in group, We have shared the tasks between us. So I was responsible for user management and the management of videos published by users.",
      Functional: ['Post management', 'Course management', 'Event management', 'Video and film management', 'Product management', 'Recruitment management'],
      url :'',
      urlbool: false,
      accesweb: '',
      Tags:  ['PHP, Symfony,Java,JavaFX, codenameone'],
      company:'Esprit',
      start: '2020',
      end: '2020',
    },
      {id: 5, 
        name: "Design cuisine", 
        description: "A web application that was created in collaboration with a furniture sales company.",
        photo: "img/projects/designcuisine.png",
        album: [ {photo: "img/projects/5/photo1.png"},
        {photo: "img/projects/5/photo2.png"},
        {photo: "img/projects/5/photo3.png"},
        {photo: "img/projects/5/photo4.png"}
        ],
        description2: "This project is carried out by 6 people for 5 months. It was for a real customer who expressed a desire to create a website in order to present his activities and products and create a direct link with his customers. An attractive, dynamic and interactive website, both for its administration and for its use, is then necessary for the proper functioning and internal and external communication of such a structure.",
        Functional: ['User and contact management', 'Product management', 'Order management', 'Employee management', 'Delivery management', 'After-sales service management'],
        url :'',
        urlbool: false,
        accesweb: '',
        Tags:  ['HTML,CSS ,Oracle'],
        company:'Esprit',
        start: '2019',
        end: '2019',
    },
    { id: 4, 
      name: "Smarket", 
      description: "Smarket allows the user to manage a supermarket in an easier way.",
      photo: "img/projects/smarket.png",
      album: [ {photo: "img/projects/4/photo1.png"},
      {photo: "img/projects/4/photo2.png"},
      {photo: "img/projects/4/photo3.png"},
      {photo: "img/projects/4/photo4.png"},
      {photo: "img/projects/4/photo5.png"}
      ],
      description2:"Smarket is an application that allows the user to manage a supermarket in an easier way. This application consists of an application for stock management, trolley management, cash management, safety management and parking management.",
      Functional: ['Product management', 'Trolley management', 'Shelf management', 'Order management', 'Employee management', 'Supplier management'],
      url :'',
      urlbool: false,
      accesweb: '',
      Tags:  ['Api Qt, c++, Oracle, Arduino'],
      company:'Esprit',
      start: '2018',
      end: '2018',
    }




];

export default Projects;